Title
========================================================
```{r}
library(ggplot2)
library(stringr)
library(mapproj)
library(ggmap)
library(igraph)
library(Matrix)
library(plyr)
library(spatstat)
library(rgdal)
library(spam)
```


```{r}
stops <- read.csv("../../../data/full_greater_sydney_gtfs_static/stops.txt")
stops <- within(stops, {
  stop_code <- factor(stop_code)
  location_type <- factor(location_type)
  wheelchair_boarding <- factor(wheelchair_boarding)
})

# sydney <- get_map("sydney", zoom = 9)

```

clustering
----------
```{r}
# ggmap(sydney) + geom_point(data = stops, aes(x = stop_lon, y = stop_lat, colour = group0), size = 0.8) + coord_map()

# The proper way -- takes ages
# stops.dist <- dist(x = stops[, c("stop_lat", "stop_lon")],  method = function(x, y) { Ellipsoidal.Distance(x[1], x[2], y[1], y[2])$dist })

# Still slow and it fails
# Manhattan distnace
# stops.dist <- dist(x = stops[, c("stop_lat", "stop_lon")],  method = "manhattan") * 100
# stops.dist[stops.dist > 0.1] <- 0
# m <- as.matrix(stops.dist)
# stops.graph <- graph.adjacency(stops.dist, mode = "undirected")

# convert to UTM
latlon <- stops[, c("stop_lat", "stop_lon")]
coordinates(latlon) <- ~ stop_lon + stop_lat
proj4string(latlon) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84")
utm <- as.data.frame(spTransform(latlon, CRS("+proj=utm +zone=56 ellps=WGS84")))
names(utm) <- c("utm_lon", "utm_lat")
stops <- cbind(stops, utm)

stops.dist <- nearest.dist(stops[, c("utm_lat", "utm_lon")], delta = 150, upper = NULL)
edgelist <- subset(data.frame(summary(as.dgCMatrix.spam(stops.dist))), x > 0)
names(edgelist) <- c("from", "to", "distance")
stops.g <- graph.data.frame(edgelist, directed = F)

# Let's use Scala!
# java -jar target/scala-2.10/StopsClustering-assembly-1.0.jar < data/full_greater_sydney_gtfs_static/stops.txt > stops.txt

edgelist <- read.csv("../../../stops.txt", header = FALSE, col.names = c("from", "to", "distance"))
stops.g <- graph.data.frame(edgelist, directed = F)

# some utility functions
lookup_stops <- function(clusters, stops, graph) {
  ldply(clusters, .fun = function(clique, data, graph) {
    d <- subset(data, stop_id %in% V(graph)$name[clique])
    d$cluster = paste(round(mean(d$stop_lat), digits = 2), round(mean(d$stop_lon), digits = 2), sep = " ")
    d
  }, data = stops, graph = graph)
}

map_object <- function(center, zoom) {
  ggmap(get_map(center, zoom))
}

cluster_stops <- function(stops, graph, loops = 10) {
  cliques <- largest.cliques(graph)
  clusters <- lookup_stops(cliques, stops, graph)
  graph <- delete.vertices(graph, unlist(cliques))
  
  if (length(V(graph)) > 0 && loops > 0) {
    clusters <- rbind(clusters, cluster_stops(stops, graph, loops - 1))
  }
  
  clusters
}

```

```{r}
rr <- function(index) { floor(-0.5 + sqrt(0.25 + 2 * index)) }
cc <- function(index) { r <- rr(index); index - r * (r + 1) / 2;}
```

```{r, message=FALSE, tidy=FALSE, fig.width=10, fig.height=10}

changes <- merge(old.stops, new.stops, by = c("stop_id"), all = T, suffixes = c(".old", ".new"))

changes$f1 <- with(changes, 
  ifelse(is.na(stop_name.old), "missing.old", 
         ifelse(is.na(stop_name.new), "missing.new", as.character(stop_name.old) == as.character(stop_name.new)
  ))
)
changes$f2 <- with(changes, stop_lat.old == stop_lat.new & stop_lon.old == stop_lon.new)

changes$change <- factor(with(changes, 
  ifelse(f1 == T & f2 == T, "none", 
         ifelse(f1 == T & f2 == F, "position", 
                ifelse(f1 == F & f2 == T, "name", 
                       ifelse(f1 == F & f2 == F, "name & position", 
                              ifelse(is.na(f2) & f1 == "missing.new", "removed", 
                                     ifelse(is.na(f2) & f1 == "missing.old", "added", NA
  ))))))
))

changes$lat <- with(changes, ifelse(is.na(stop_lat.new), stop_lat.old, stop_lat.new))
changes$lon <- with(changes, ifelse(is.na(stop_lon.new), stop_lon.old, stop_lon.new))

changes.sub <- subset(changes, change != "none")

base <- with(changes.sub, get_map(paste(mean(lat), mean(lon), sep = " "), zoom = 8, color = "bw"))

ggmap(base) + 
  geom_point(data = changes.sub, aes(x = lon, y = lat, colour = change)) +
  ggtitle("Stops changes")

```
